authsource: null
host: mongodb://localhost
logdir: null
mongoclient_kwargs: {}
name: null
password: null
port: null
ssl: false
ssl_ca_certs: null
ssl_certfile: null
ssl_keyfile: null
ssl_pem_passphrase: null
strm_lvl: INFO
uri_mode: true
user_indices: []
username: null
wf_user_indices: []
